queue: Hosted VS2017

trigger:
- master
- features/*
- release/*

steps:
- task: BatchScript@1
  displayName: Set environment variables
  inputs:
    filename: '$(Build.SourcesDirectory)\.vsts\vsts.set-environment-variables.bat'
    modifyEnvironment: true
  
- task: DotNetCoreInstaller@0
  displayName: Use .NET Core SDK 2.2
  inputs:
    version: 2.2.101

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'src/*.sln'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: build
    projects: 'src/*.sln'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'src/**/*Test.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    projects: 'src/*.sln'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'

